Repository Codivas/portal-codivas, pull requests merged in 2022-10, with the labels that each got.

#95 closes #90
  src/Components/Header.jsx
Labels: hacktoberfest, front end

#96 closes #94
  src/Components/Footer.jsx
  src/Pages/Login.jsx
Labels: hacktoberfest

#101 update readme image
  README.md
Labels: documentation, hacktoberfest

#102 closes #89
  src/Components/Header.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#109 update readme with instructions
  README.md
Labels: documentation, hacktoberfest

#114 Add logout button to header component
  src/Components/Header.jsx
Labels: hacktoberfest, hacktoberfest-accepted
